apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: pod-agent
    namespace: jenkins
spec:
  initContainers:
    - name: init-docker
      image: busybox
      command:
        - sh
        - -c
        - cp /etc/config/daemon.json /etc/docker/daemon.json
      volumeMounts:
        - name: docker-config
          mountPath: /etc/config
        - name: docker-socket
          mountPath: /var/run/docker.sock
  containers:
    - name: golang
      image: golang:1.22.5-alpine
      command:
        - cat
      tty: true
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /etc/docker
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-config
      configMap:
        name: docker-daemon-config
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock