apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: jenkins
  labels:
    jenkins: pod-golang
spec:
  containers:
    - name: docker
      image: docker:latest
      securityContext:
        privileged: true
      command: ["sh","-c"]
      args:
      - |
        echo "192.168.100.241 dcr.bondhan.local" >> /etc/hosts
        dockerd
      volumeMounts:
        - name: docker-config
          mountPath: /etc/docker/
  volumes:
    - name: docker-config
      configMap:
        name: docker-daemon-config