apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: jenkins
  labels:
    jenkins: pod-golang
spec:
  containers:
    - name: docker
      image: docker:latest
      command:
        - sh
        - -c
        - |
          dockerd
          echo "192.168.100.241 dcr.bondhan.local" >> /etc/hosts
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /etc/docker/
        - name: docker-sock
          mountPath: /var/run/
      securityContext:
        privileged: true
  volumes:
    - name: docker-config
      configMap:
        name: docker-daemon-config
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock