apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod-golang
  namespace: jenkins
  labels:
    jenkins: pod-golang
spec:
  containers:
    - name: golang
      image: golang:1.22.5-alpine
      command:
        - cat
      tty: true
    - name: docker
      image: docker:latest
      command:
        - sh
        - -c
        - cp /etc/config/daemon.json /etc/docker/daemon.json
        - cat /etc/docker/daemon.json
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /etc/config/daemon.json
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-config
      configMap:
        name: docker-daemon-config
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock